//photos des vetements 
const shop = [
    {
        id:1,
        attachment:"images/banner/boutique-scenario-aigues-devanture.mortes.jpg",
        alt:"boutique scenario des vetements pour la femme a aigues mortes"
    },
    {
        id:2,
        attachment:"images/banner/boutique-scenario-aigues-mortes.jpg",
        alt:""
    },
    {
        id:3,
        attachment:"images/banner/boutique-scenario-chemise-aigues-mortes-habits-femme.jpg",
        alt:""
    },
    {
        id:4,
        attachment:"images/banner/boutique-scenario-chemises-femme.jpg",
        alt:""
    },
    {
        id:5,
        attachment:"images/banner/boutique-scenario-creatrice-aigues-mortes.jpg",
        alt:""
    },
    {
        id:6,
        attachment:"images/banner/boutique-scenario-femme-aigues-mortes.jpg",
        alt:""
    },
    {
        id:7,
        attachment:"images/banner/boutique-scenario-femme-robe.aigues-mortes.jpg",
        alt:""
    },
    {
        id:8,
        attachment:"images/banner/boutique-scenario-hauts-femme.aigues-mortes.jpg",
        alt:""
    },
    {
        id:9,
        attachment:"images/banner/boutique-scenario-jeans.aigues-mortes.jpg",
        alt:""
    },
    {
        id:10,
        attachment:"images/banner/boutique-scenario-partie-fillette.aigues-mortes.jpg",
        alt:""
    },
    {
        id:11,
        attachment:"images/banner/boutique-scenario-tenues-feminines.aigues-mortes.jpg",
        alt:""
    }
]